name: init_pro
description: >
  A command-line tool for Flutter projects to generate boilerplate code 
  and clean architecture setup.

version: 0.4.0+3

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.6.0
  io: ^1.0.5
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  init-pro: init_pro

# Metadata
homepage: https://github.com/NagesoHaile/init-pro
repository: https://github.com/NagesoHaile/init-pro
issue_tracker: https://github.com/NagesoHaile/init-pro/issues
